[tool.poetry]
name = "etl-backup-case"
version = "0.1.0"
description = ""
authors = ["Johmar Souza <johmar.o.souza@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
boto3 = "^1.35.6"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
